### ISSUE TITLE
Clarify min-gas-price behaviour 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#310] opened 2020-04-07 05:46 UTC
From https://github.com/hyperledger/besu/issues/653

> Node silently drops remote transactions with gasPrice < nodes minimum gas price.

> Documentation on min-gas-price needs to explicitly call this out especially for a zero gas network.

**Comment by bgravenorst** [comment] 2020-11-17 21:56
This is a duplicate of https://github.com/hyperledger/besu-docs/issues/322

**Closed** 2020-11-20 06:22 UTC
Labels: duplicate
