### ISSUE TITLE
Make host-whitelist description clearer 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#309] opened 2020-04-06 21:41 UTC
From https://github.com/hyperledger/besu/issues/615: 

> Unfortunately the documentation for the host-whitelist option is not completely clear. If you expose RPC services externally then you need to add the appropriate hostname or ip to the host-whitelist. By default a Besu node only allows JSON-RPC requests from localhost/127.0.0.1.

Note: Issue not yet resolved so may be more relevant information added.

**Comment by grantnoble** [comment] 2020-04-16 05:29
Duplicate of issue #321 and fixed by PR #323. Suggest closing.

**Comment by bgravenorst** [comment] 2021-02-12 02:13
I think this can be closed

**Closed** 2021-02-12 16:28 UTC
Labels: duplicate
